version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=qwerty
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    container_name: redis
    ports:
      - '6381:6379'

  app:
    build: .
    tty: true
    command: >
      bash -c "python manage.py migrate --noinput
      && python manage.py csu
      && python manage.py runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO
    depends_on:
      - redis
      - app


  celery_beat:
    build: .
    tty: true
    command: celery -A config beat -l INFO
    depends_on:
      - redis
      - app

volumes:
  pg_data: