# Generated by Django 4.2.6 on 2023-10-23 12:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150, verbose_name='место')),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 10, 23, 12, 31, 50, 357683), verbose_name='время')),
                ('action', models.CharField(max_length=150, verbose_name='действие')),
                ('is_pleasant_habit', models.BooleanField(blank=True, default=False, null=True, verbose_name='признак приятной привычки')),
                ('periodicity', models.PositiveSmallIntegerField(choices=[(1, 'каждый день'), (2, 'раз в два дня'), (3, 'раз в три дня'), (4, 'раз в четыре дня'), (5, 'раз в пять дней'), (6, 'раз в шесть дней'), (7, 'раз в семь дней')], default=1, verbose_name='периодичность')),
                ('reward', models.TextField(blank=True, null=True, verbose_name='вознаграждение')),
                ('lead_time', models.TimeField(verbose_name='время выполнения')),
                ('is_published', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habit', to='habit.habit', verbose_name='связанная привычка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habit', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
