# Generated by Django 4.2.6 on 2023-10-23 15:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='is_pleasant_habit',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='приятная привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habit', to='habit.habit', verbose_name='приятная привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 15, 2, 29, 4024), verbose_name='время'),
        ),
    ]
