# Generated by Django 4.2.6 on 2023-10-23 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_alter_habit_is_pleasant_habit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 15, 12, 11, 214617), verbose_name='время'),
        ),
    ]
